/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculofiguras;

import java.util.Scanner;

/**
 *
 * @author Oficina
 */
public class formulario extends javax.swing.JFrame {

    formulas formula = new formulas();
    Scanner teclado = new Scanner(System.in);
    int num1 = 0;
    int num2 = 0;
    int lado;

    public formulario() {
        initComponents();
        configPanelPrincipal();
        panelPrincipal();
        configPanelCuadrado();
        configPanelTriangulo();

    }

    //Configuración Panel Princpal
    public void configPanelPrincipal() {
        this.setTitle("Cálculo Figuras Geométricas");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    //Configuración Panel Triangulo
    public void configPanelTriangulo() {
        imagenesTriangulo.remove(equilatero);
        imagenesTriangulo.remove(isosceles);
        comboTriangulo.setSelectedIndex(0);
        resultadoTriangulo.setEditable(false);
    }

    public void configPanelCuadrado() {
        resultadoCuadrado.setEditable(false);
    }

    public void borrarStringCuadrado() {
        valor1Cuadrado.setText(null);
        resultadoCuadrado.setText(null);
    }

    public void borrarStringTriangulo() {
        valor1Triangulo.setText(null);
        valor2Triangulo.setText(null);
        resultadoTriangulo.setText(null);
    }

    public void borrarStringCirculo() {

    }

    //Configuración posicion Panel Principal
    public void panelPrincipal() {
        panelCuadrado.setVisible(false);
        this.remove(panelCuadrado);
        panelCirculo.setVisible(false);
        this.remove(panelCirculo);
        panelTriangulo.setVisible(false);
        this.remove(panelTriangulo);
        this.add(panelPrincipal);
        panelPrincipal.setVisible(true);
    }

    //Configuración posicion Panel Cuadrado
    public void panelCuadrado() {
        panelTriangulo.setVisible(false);
        this.remove(panelTriangulo);
        panelCirculo.setVisible(false);
        this.remove(panelCirculo);
        panelPrincipal.setVisible(false);
        this.remove(panelPrincipal);
        this.add(panelCuadrado);
        panelCuadrado.setVisible(true);
    }

    //Configuración posicion Panel Triangulo
    public void panelTriangulo() {
        panelCuadrado.setVisible(false);
        this.remove(panelCuadrado);
        panelCirculo.setVisible(false);
        this.remove(panelCirculo);
        panelPrincipal.setVisible(false);
        this.remove(panelPrincipal);
        this.add(panelTriangulo);
        panelTriangulo.setVisible(true);
    }

    //Configuración posicion Panel Circulo
    public void panelCirculo() {
        panelCuadrado.setVisible(false);
        this.remove(panelCuadrado);
        panelCirculo.setVisible(false);
        this.remove(panelCirculo);
        panelTriangulo.setVisible(false);
        this.remove(panelTriangulo);
        this.add(panelPrincipal);
        panelPrincipal.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTriangulo = new javax.swing.JPanel();
        b2Inicio = new javax.swing.JButton();
        b2Cuadrado = new javax.swing.JButton();
        b3Circulo = new javax.swing.JButton();
        calTriangulo = new javax.swing.JButton();
        comboTriangulo = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        imagenesTriangulo = new javax.swing.JPanel();
        rectangulo = new javax.swing.JLabel();
        equilatero = new javax.swing.JLabel();
        isosceles = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        valor1Triangulo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        valor2Triangulo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        resultadoTriangulo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        panelPrincipal = new javax.swing.JPanel();
        b1Cuadrado = new javax.swing.JButton();
        b1Triangulo = new javax.swing.JButton();
        b1Circulo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelCuadrado = new javax.swing.JPanel();
        b1Inicio = new javax.swing.JButton();
        b2Triangulo = new javax.swing.JButton();
        b2Circulo = new javax.swing.JButton();
        calCuadrado = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ladolabel1 = new javax.swing.JLabel();
        labelAreaCuadrado = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        valor1Cuadrado = new javax.swing.JTextField();
        resultadoCuadrado = new javax.swing.JTextField();
        panelCirculo = new javax.swing.JPanel();
        b3Inicio = new javax.swing.JButton();
        b3Cuadrado = new javax.swing.JButton();
        b3Triangulo = new javax.swing.JButton();
        calcCirculo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 350));
        getContentPane().setLayout(null);

        b2Inicio.setText("Principal");
        b2Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2InicioActionPerformed(evt);
            }
        });

        b2Cuadrado.setText("Cuadrado");
        b2Cuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2CuadradoActionPerformed(evt);
            }
        });

        b3Circulo.setText("Circulo");
        b3Circulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3CirculoActionPerformed(evt);
            }
        });

        calTriangulo.setText("Calcular Area");
        calTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calTrianguloActionPerformed(evt);
            }
        });

        comboTriangulo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rectangulo", "Equilatero", "Isosceles" }));
        comboTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTrianguloActionPerformed(evt);
            }
        });

        imagenesTriangulo.setLayout(null);

        rectangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/trianguloRectangulo.png"))); // NOI18N
        imagenesTriangulo.add(rectangulo);
        rectangulo.setBounds(0, 0, 91, 93);

        equilatero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/trianguloEquilatero.png"))); // NOI18N
        imagenesTriangulo.add(equilatero);
        equilatero.setBounds(0, 0, 91, 93);

        isosceles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/trianguloIsosceles.png"))); // NOI18N
        imagenesTriangulo.add(isosceles);
        isosceles.setBounds(0, 0, 91, 93);

        jLabel8.setText("Altura");

        jLabel9.setText("Base");

        jLabel10.setText("Area");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cuadrado.png"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/circulo.png"))); // NOI18N

        javax.swing.GroupLayout panelTrianguloLayout = new javax.swing.GroupLayout(panelTriangulo);
        panelTriangulo.setLayout(panelTrianguloLayout);
        panelTrianguloLayout.setHorizontalGroup(
            panelTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(panelTrianguloLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(b2Inicio)
                .addGap(35, 35, 35)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(panelTrianguloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imagenesTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(panelTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calTriangulo)
                    .addGroup(panelTrianguloLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(comboTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(panelTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(valor1Triangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(resultadoTriangulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                        .addComponent(valor2Triangulo, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTrianguloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b2Cuadrado)
                .addGap(44, 44, 44)
                .addComponent(b3Circulo)
                .addGap(50, 50, 50))
        );
        panelTrianguloLayout.setVerticalGroup(
            panelTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTrianguloLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(panelTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelTrianguloLayout.createSequentialGroup()
                            .addComponent(calTriangulo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(imagenesTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTrianguloLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valor1Triangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valor2Triangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultadoTriangulo)
                .addGroup(panelTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTrianguloLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelTrianguloLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(b2Inicio)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b3Circulo)
                    .addComponent(b2Cuadrado))
                .addGap(187, 187, 187))
        );

        getContentPane().add(panelTriangulo);
        panelTriangulo.setBounds(0, 0, 400, 300);

        b1Cuadrado.setText("Cuadrado");
        b1Cuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1CuadradoActionPerformed(evt);
            }
        });

        b1Triangulo.setText("Triangulo");
        b1Triangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1TrianguloActionPerformed(evt);
            }
        });

        b1Circulo.setText("Circulo");
        b1Circulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1CirculoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Vijaya", 1, 36)); // NOI18N
        jLabel1.setText("Selecciona una figura");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cuadrado.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/trianguloEquilatero.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/circulo.png"))); // NOI18N

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(b1Cuadrado)
                        .addGap(37, 37, 37)
                        .addComponent(b1Triangulo)
                        .addGap(18, 31, Short.MAX_VALUE)))
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                        .addComponent(b1Circulo)
                        .addGap(39, 39, 39))))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)))
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b1Circulo)
                    .addComponent(b1Cuadrado)
                    .addComponent(b1Triangulo))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        getContentPane().add(panelPrincipal);
        panelPrincipal.setBounds(0, 0, 400, 300);

        b1Inicio.setText("Principal");
        b1Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1InicioActionPerformed(evt);
            }
        });

        b2Triangulo.setText("Triangulo");
        b2Triangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2TrianguloActionPerformed(evt);
            }
        });

        b2Circulo.setText("Circulo");
        b2Circulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2CirculoActionPerformed(evt);
            }
        });

        calCuadrado.setText("Calcular Area");
        calCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calCuadradoActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/trianguloEquilatero.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/circulo.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cuadrado.png"))); // NOI18N

        ladolabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        ladolabel1.setText("Lado");

        labelAreaCuadrado.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        labelAreaCuadrado.setText("Area");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/formulaCuadrado.png"))); // NOI18N

        javax.swing.GroupLayout panelCuadradoLayout = new javax.swing.GroupLayout(panelCuadrado);
        panelCuadrado.setLayout(panelCuadradoLayout);
        panelCuadradoLayout.setHorizontalGroup(
            panelCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuadradoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelCuadradoLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(labelAreaCuadrado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resultadoCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCuadradoLayout.createSequentialGroup()
                        .addComponent(calCuadrado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ladolabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valor1Cuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(383, 383, 383))
            .addGroup(panelCuadradoLayout.createSequentialGroup()
                .addGroup(panelCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelCuadradoLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(b1Inicio)
                        .addGap(33, 33, 33)
                        .addGroup(panelCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCuadradoLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(b2Triangulo))
                            .addComponent(jLabel5))
                        .addGroup(panelCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCuadradoLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6))
                            .addGroup(panelCuadradoLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(b2Circulo)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCuadradoLayout.setVerticalGroup(
            panelCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCuadradoLayout.createSequentialGroup()
                .addGroup(panelCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCuadradoLayout.createSequentialGroup()
                        .addGroup(panelCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCuadradoLayout.createSequentialGroup()
                                .addContainerGap(21, Short.MAX_VALUE)
                                .addGroup(panelCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(valor1Cuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ladolabel1)
                                    .addComponent(calCuadrado))
                                .addGroup(panelCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelCuadradoLayout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addGroup(panelCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(resultadoCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelAreaCuadrado))
                                        .addGap(39, 39, 39))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCuadradoLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18))))
                            .addGroup(panelCuadradoLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(panelCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCuadradoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(b1Inicio)
                        .addGap(28, 28, 28)))
                .addGroup(panelCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b2Circulo)
                    .addComponent(b2Triangulo))
                .addGap(20, 20, 20))
        );

        getContentPane().add(panelCuadrado);
        panelCuadrado.setBounds(0, 0, 400, 300);

        b3Inicio.setText("jButton1");
        b3Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3InicioActionPerformed(evt);
            }
        });

        b3Cuadrado.setText("jButton3");
        b3Cuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3CuadradoActionPerformed(evt);
            }
        });

        b3Triangulo.setText("jButton2");
        b3Triangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3TrianguloActionPerformed(evt);
            }
        });

        calcCirculo.setText("jButton4");
        calcCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcCirculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCirculoLayout = new javax.swing.GroupLayout(panelCirculo);
        panelCirculo.setLayout(panelCirculoLayout);
        panelCirculoLayout.setHorizontalGroup(
            panelCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(panelCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelCirculoLayout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addGroup(panelCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(b3Triangulo)
                        .addGroup(panelCirculoLayout.createSequentialGroup()
                            .addGap(264, 264, 264)
                            .addComponent(b3Inicio))
                        .addGroup(panelCirculoLayout.createSequentialGroup()
                            .addGap(125, 125, 125)
                            .addComponent(b3Cuadrado)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(calcCirculo)
                            .addGap(14, 14, 14)))
                    .addGap(32, 32, 32)))
        );
        panelCirculoLayout.setVerticalGroup(
            panelCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(panelCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelCirculoLayout.createSequentialGroup()
                    .addGap(58, 58, 58)
                    .addComponent(b3Inicio)
                    .addGap(108, 108, 108)
                    .addComponent(b3Triangulo)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(panelCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(b3Cuadrado)
                        .addComponent(calcCirculo))
                    .addContainerGap(59, Short.MAX_VALUE)))
        );

        getContentPane().add(panelCirculo);
        panelCirculo.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Buttons Panel Principal
    private void b1CuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1CuadradoActionPerformed
        panelCuadrado();
        borrarStringCuadrado();
    }//GEN-LAST:event_b1CuadradoActionPerformed

    private void b1TrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1TrianguloActionPerformed
        panelTriangulo();
    }//GEN-LAST:event_b1TrianguloActionPerformed

    private void b1CirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1CirculoActionPerformed
        panelCirculo();
    }//GEN-LAST:event_b1CirculoActionPerformed

    //Buttons Panel Cuadrado
    private void b1InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1InicioActionPerformed
        panelPrincipal();
        borrarStringCuadrado();
    }//GEN-LAST:event_b1InicioActionPerformed

    private void b2TrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2TrianguloActionPerformed
        panelTriangulo();
        borrarStringCuadrado();
    }//GEN-LAST:event_b2TrianguloActionPerformed

    private void b2CirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2CirculoActionPerformed
        panelCirculo();
        borrarStringCuadrado();
    }//GEN-LAST:event_b2CirculoActionPerformed

    private void calCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calCuadradoActionPerformed
        num1 = Integer.parseInt(valor1Cuadrado.getText());
        formula.formulaCuadrado(num1);
        resultadoCuadrado.setText(String.valueOf(formula.getArea()));
    }//GEN-LAST:event_calCuadradoActionPerformed

    //Buttons Panel Triangulo
    private void b2InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2InicioActionPerformed
        panelPrincipal();
        borrarStringTriangulo();

    }//GEN-LAST:event_b2InicioActionPerformed

    private void b2CuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2CuadradoActionPerformed
        panelCuadrado();
        borrarStringTriangulo();
    }//GEN-LAST:event_b2CuadradoActionPerformed

    private void b3CirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3CirculoActionPerformed
        panelCirculo();
        borrarStringTriangulo();
    }//GEN-LAST:event_b3CirculoActionPerformed

    private void calTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calTrianguloActionPerformed
        if (comboTriangulo.getSelectedIndex() == 0) {
            num1 = Integer.parseInt(valor1Triangulo.getText());
            num2 = Integer.parseInt(valor2Triangulo.getText());
            formula.formulaTrianRectangulo(num1, num2);
            resultadoTriangulo.setText(String.valueOf(formula.getArea()));
        }
        if (comboTriangulo.getSelectedIndex() == 1) {
            num1 = Integer.parseInt(valor1Triangulo.getText());
            num2 = Integer.parseInt(valor2Triangulo.getText());
            formula.formulaTrianRectangulo(num1, num2);
            resultadoTriangulo.setText(String.valueOf(formula.getArea()));
        }
    }//GEN-LAST:event_calTrianguloActionPerformed

    //Buttons Panel Circulo
    private void b3InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3InicioActionPerformed
        panelPrincipal();
        borrarStringCirculo();
    }//GEN-LAST:event_b3InicioActionPerformed

    private void b3CuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3CuadradoActionPerformed
        panelCuadrado();
        borrarStringCirculo();
    }//GEN-LAST:event_b3CuadradoActionPerformed

    private void b3TrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3TrianguloActionPerformed
        panelTriangulo();
        borrarStringCirculo();
    }//GEN-LAST:event_b3TrianguloActionPerformed

    private void calcCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcCirculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calcCirculoActionPerformed

    private void comboTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTrianguloActionPerformed
        if (comboTriangulo.getSelectedIndex() == 0) {
            imagenesTriangulo.remove(equilatero);
            equilatero.setVisible(false);
            imagenesTriangulo.remove(isosceles);
            isosceles.setVisible(false);
            imagenesTriangulo.add(rectangulo);
            rectangulo.setVisible(true);
            borrarStringTriangulo();
        }
        if (comboTriangulo.getSelectedIndex() == 1) {
            imagenesTriangulo.add(equilatero);
            equilatero.setVisible(true);
            imagenesTriangulo.remove(isosceles);
            isosceles.setVisible(false);
            imagenesTriangulo.remove(rectangulo);
            rectangulo.setVisible(false);
            borrarStringTriangulo();

        }
        if (comboTriangulo.getSelectedIndex() == 2) {
            imagenesTriangulo.remove(equilatero);
            equilatero.setVisible(false);
            imagenesTriangulo.add(isosceles);
            isosceles.setVisible(true);
            imagenesTriangulo.remove(rectangulo);
            rectangulo.setVisible(false);
            borrarStringTriangulo();
        }
    }//GEN-LAST:event_comboTrianguloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1Circulo;
    private javax.swing.JButton b1Cuadrado;
    private javax.swing.JButton b1Inicio;
    private javax.swing.JButton b1Triangulo;
    private javax.swing.JButton b2Circulo;
    private javax.swing.JButton b2Cuadrado;
    private javax.swing.JButton b2Inicio;
    private javax.swing.JButton b2Triangulo;
    private javax.swing.JButton b3Circulo;
    private javax.swing.JButton b3Cuadrado;
    private javax.swing.JButton b3Inicio;
    private javax.swing.JButton b3Triangulo;
    private javax.swing.JButton calCuadrado;
    private javax.swing.JButton calTriangulo;
    private javax.swing.JButton calcCirculo;
    private javax.swing.JComboBox<String> comboTriangulo;
    private javax.swing.JLabel equilatero;
    private javax.swing.JPanel imagenesTriangulo;
    private javax.swing.JLabel isosceles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelAreaCuadrado;
    private javax.swing.JLabel ladolabel1;
    private javax.swing.JPanel panelCirculo;
    private javax.swing.JPanel panelCuadrado;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelTriangulo;
    private javax.swing.JLabel rectangulo;
    private javax.swing.JTextField resultadoCuadrado;
    private javax.swing.JTextField resultadoTriangulo;
    private javax.swing.JTextField valor1Cuadrado;
    private javax.swing.JTextField valor1Triangulo;
    private javax.swing.JTextField valor2Triangulo;
    // End of variables declaration//GEN-END:variables
}
